const TOPICS={ACL:10,Tendinopathie:9,Klettern:10,"Return to Sport":10,Wirbelsäule:8,Schulter:8,"Digital Health":8,Schmerz:7};
const DEMO=[
{id:'d1',title:'Criteria-based return to sport after ACL reconstruction',abstract:'Eine kriteriumsbasierte Progression kombiniert Kraftsymmetrie, Sprungleistung, Belastungsverträglichkeit und psychologische Bereitschaft.',journal:'Sports Medicine',year:2026,topic:'ACL',type:'Review',evidence:'hoch',url:'https://pubmed.ncbi.nlm.nih.gov/',score:92,impact:'Standardprotokoll um explizite Belastungsverträglichkeit und psychologische Bereitschaft ergänzen.'},
{id:'d2',title:'Load management in lower-limb tendinopathy',abstract:'Progressive Belastung bleibt zentral; starre Schmerzgrenzen werden zunehmend durch individuelle Reaktionsmodelle ersetzt.',journal:'JOSPT',year:2026,topic:'Tendinopathie',type:'Clinical Review',evidence:'mittel',url:'https://pubmed.ncbi.nlm.nih.gov/',score:86,impact:'24-Stunden-Reaktion und Leistungsmarker stärker gewichten als einen einzelnen Schmerz-Cut-off.'},
{id:'d3',title:'Finger pulley injuries in climbers: rehabilitation considerations',abstract:'Die Publikation beschreibt stufenweise Gewebebelastung, sportspezifische Griffprogression und Return-to-Climb-Kriterien.',journal:'Physical Therapy in Sport',year:2026,topic:'Klettern',type:'Narrative Review',evidence:'niedrig–mittel',url:'https://pubmed.ncbi.nlm.nih.gov/',score:81,impact:'Interessant für ein kletterspezifisches Belastungsmodul; Evidenzbasis noch begrenzt.'},
{id:'d4',title:'Wearables for remote rehabilitation monitoring',abstract:'Wearables können Adhärenz und Aktivitätsdaten erfassen; klinischer Zusatznutzen hängt stark vom Workflow ab.',journal:'Journal of Physiotherapy',year:2026,topic:'Digital Health',type:'Systematic Review',evidence:'mittel',url:'https://pubmed.ncbi.nlm.nih.gov/',score:73,impact:'Für BareMotion relevant, aber nur bei klarer Entscheidungslogik statt bloßer Datensammlung.'},
{id:'d5',title:'Manual therapy for non-specific low back pain',abstract:'Kurzfristige Effekte sind möglich, langfristige Unterschiede gegenüber aktiven Ansätzen bleiben gering.',journal:'Musculoskeletal Science and Practice',year:2026,topic:'Wirbelsäule',type:'Meta-analysis',evidence:'mittel',url:'https://pubmed.ncbi.nlm.nih.gov/',score:66,impact:'Bestätigt deine Logik: passive Maßnahmen nur als Fenster für Aktivität einsetzen.'}
];
let items=JSON.parse(localStorage.getItem('evidence-items')||'null')||DEMO,profile=JSON.parse(localStorage.getItem('evidence-profile')||'null')||TOPICS,selected='Alle';
const $=s=>document.querySelector(s),esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const feedbacks=()=>JSON.parse(localStorage.getItem('evidence-feedback')||'{}');
function calcScore(x){const f=feedbacks()[x.id];return Math.max(0,Math.min(100,Math.round((x.score||55)+((profile[x.topic]||5)-5)*2+(f==='more'?6:f==='less'?-10:0))))}
function renderFilters(){const topics=['Alle',...new Set(items.map(x=>x.topic))];$('#topicFilters').innerHTML=topics.map(t=>`<button class="chip ${selected===t?'active':''}" data-topic="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{selected=b.dataset.topic;render()})}
function renderProfile(){profile={...TOPICS,...profile};$('#profileEditor').innerHTML=Object.entries(profile).map(([k,v])=>`<label class="profile-row"><span>${esc(k)}</span><input type="range" min="1" max="10" value="${v}" data-profile="${esc(k)}"><strong>${v}</strong></label>`).join('');document.querySelectorAll('[data-profile]').forEach(i=>i.oninput=()=>i.nextElementSibling.textContent=i.value)}
function card(x){const label=x.computed>=75?'Praxisrelevant':x.computed>=55?'Beobachten':'Aussortiert';return `<article class="card"><div><div class="meta"><span class="badge">${esc(x.topic)}</span><span class="badge">${esc(x.type||'Studie')}</span><span class="badge">Evidenz: ${esc(x.evidence||'unklar')}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.abstract||'Kein Abstract verfügbar.')}</p><div class="actions"><button data-open="${esc(x.id)}">Einordnung öffnen</button><button data-feedback="more" data-id="${esc(x.id)}">Mehr davon</button><button data-feedback="less" data-id="${esc(x.id)}">Weniger davon</button></div></div><div class="score">${x.computed}<small>${label}</small></div></article>`}
function render(){renderFilters();const q=$('#searchInput').value.toLowerCase(),visible=items.map(x=>({...x,computed:calcScore(x)})).filter(x=>(selected==='Alle'||x.topic===selected)&&(`${x.title} ${x.abstract} ${x.topic}`.toLowerCase().includes(q))).sort((a,b)=>b.computed-a.computed);$('#feed').innerHTML=visible.length?visible.map(card).join(''):'<div class="empty">Keine passenden Meldungen.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.open));document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>setFeedback(b.dataset.id,b.dataset.feedback));const all=items.map(x=>({...x,computed:calcScore(x)}));$('#relevantCount').textContent=all.filter(x=>x.computed>=75).length;$('#watchCount').textContent=all.filter(x=>x.computed>=55&&x.computed<75).length;$('#discardedCount').textContent=all.filter(x=>x.computed<55).length;$('#feedbackCount').textContent=Object.keys(feedbacks()).length}
function openDetail(id){const x=items.find(i=>i.id===id);if(!x)return;$('#detailContent').innerHTML=`<p class="eyebrow">${esc(x.journal||'Quelle')} · ${esc(x.year||'')}</p><h2>${esc(x.title)}</h2><p>${esc(x.abstract||'')}</p><h3>Konsequenz für deine Arbeit</h3><p>${esc(x.impact||'Noch keine belastbare Praxisänderung ableitbar. Fachliche Volltextprüfung erforderlich.')}</p><p><a href="${esc(x.url||'#')}" target="_blank" rel="noreferrer">Quelle öffnen</a></p>`;$('#detailDialog').showModal()}
function setFeedback(id,value){const f=feedbacks();f[id]=value;localStorage.setItem('evidence-feedback',JSON.stringify(f));render()}
async function scan(){const btn=$('#scanButton');btn.disabled=true;btn.textContent='Scan läuft …';$('#scanStatus').textContent='Europe PMC wird durchsucht';const query='(physiotherapy OR "physical therapy") AND (sports OR rehabilitation OR tendon OR ACL OR climbing) AND FIRST_PDATE:[2025-01-01 TO 2026-12-31]';try{const url='https://www.ebi.ac.uk/europepmc/webservices/rest/search?format=json&pageSize=30&sort_date:y&query='+encodeURIComponent(query),r=await fetch(url);if(!r.ok)throw new Error();const data=await r.json(),fresh=(data.resultList?.result||[]).map(normalize).filter(Boolean);if(!fresh.length)throw new Error();items=[...fresh,...DEMO].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,35);localStorage.setItem('evidence-items',JSON.stringify(items));$('#scanStatus').textContent=`${fresh.length} aktuelle Treffer analysiert`;$('#briefingTitle').textContent='Aktueller Evidence-Scan'}catch(e){$('#scanStatus').textContent='Live-Scan nicht erreichbar – Demo bleibt aktiv'}finally{btn.disabled=false;btn.textContent='Aktuellen Scan starten';render()}}
function normalize(r){if(!r.title)return null;const text=(r.title+' '+(r.authorString||'')).toLowerCase();let topic=text.includes('acl')||text.includes('anterior cruciate')?'ACL':text.includes('tendon')?'Tendinopathie':text.includes('climb')?'Klettern':text.includes('shoulder')?'Schulter':text.includes('spine')||text.includes('back pain')?'Wirbelsäule':text.includes('digital')||text.includes('wearable')?'Digital Health':'Return to Sport';const type=(r.pubType||'Study').split(';')[0],quality=/systematic review|meta-analysis|guideline/i.test(r.pubType||'')?18:/randomized/i.test(r.pubType||'')?14:5,score=Math.min(96,48+quality+(profile[topic]||5)*3);return{id:r.pmid||r.pmcid||r.id,title:r.title,abstract:`${r.authorString||'Autor:innen nicht angegeben'} · ${r.journalTitle||'Journal nicht angegeben'}`,journal:r.journalTitle,year:r.pubYear,topic,type,evidence:quality>=18?'hoch':quality>=14?'mittel–hoch':'vorläufig',url:r.pmid?`https://pubmed.ncbi.nlm.nih.gov/${r.pmid}/`:`https://europepmc.org/article/${r.source}/${r.id}`,score,impact:score>=75?'Priorisiert für Volltextprüfung; mögliche Relevanz für bestehende Praxisstandards.':'Beobachten, derzeit keine direkte Praxisänderung.'}}
$('#scanButton').onclick=scan;$('#searchInput').oninput=render;$('#saveProfile').onclick=()=>{document.querySelectorAll('[data-profile]').forEach(i=>profile[i.dataset.profile]=Number(i.value));localStorage.setItem('evidence-profile',JSON.stringify(profile));render();$('#scanStatus').textContent='Relevanzprofil gespeichert'};$('#closeDialog').onclick=()=>$('#detailDialog').close();renderProfile();render();